service:
  identifier: "Sungrow-1"
  model: "sungrow"
  host: "192.168.10.10"
  port: 502
  modbus_order: "CDAB"
  modbus_slave: 1
  interval: 0.1
  ems_service_read_topic: "/devices/read"
  ems_service_command_topic: "/devices/command"
  data_service_request_topic: "/data/request"
  data_service_response_topic: "/data/response"
  message_bus:
    host: "127.0.0.1"
    port: 6379
    username: "inovat"
    password: "Inovat1023!"
